# Generated by Django 4.0.2 on 2022-03-01 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('published', models.BooleanField()),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'multiple_choice'), ('fill_in_blank', 'fill_in_blank')], max_length=300)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lessonquestion',
            constraint=models.UniqueConstraint(fields=('name', 'lesson'), name='combination of lesson and name is unique'),
        ),
    ]
