# Generated by Django 4.0.2 on 2022-03-01 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lessonquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=500)),
                ('option_correct', models.BooleanField()),
                ('lesson_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessonquestion')),
            ],
        ),
    ]
