# Generated by Django 4.0.2 on 2022-03-09 06:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userlessonprogress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='min_passing_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='wanted_number_quiz_questions',
            field=models.PositiveSmallIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='min_passing_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(check=models.Q(('min_passing_score__gte', 0.0), ('min_passing_score__lte', 100.0)), name='lesson_min_passing_score_range'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.CheckConstraint(check=models.Q(('min_passing_score__gte', 0.0), ('min_passing_score__lte', 100.0)), name='topic_min_passing_score_range'),
        ),
        migrations.AddField(
            model_name='lessonparagraph',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson'),
        ),
    ]
