# Generated by Django 4.0.2 on 2022-03-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lessonparagraph_lesson_min_passing_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='content',
            new_name='content_description',
        ),
    ]
