# Generated by Django 4.0.2 on 2022-04-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_content_lesson_content_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonquestionoption',
            name='option',
            field=models.TextField(),
        ),
    ]
