# Generated by Django 4.0.2 on 2022-04-15 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_instructorrequest_pref_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorrequest',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
